### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by stefangal** [stefangal/Throw-a-dice#1]
**TODO:**
- [ ] Allow the user to input the amount of sides on a dice and how many times it should be rolled.
- [ ] Keep track of how many times each number comes up (this does not have to be displayed).
- [ ] Finally, print out how many times each number came up.
**Subgoals:**
     - [ ] Adjust your program so that if the user does not type in a number when they need to, the program will keep prompting them to type in a real number until they do so.
     - [ ] Put the program into a loop so that the user can continue to simulate dice rolls without having to restart the entire program.
     - [ ] In addition to printing out how many times each side appeared, also print out the percentage it appeared. If you can, round the percentage to 4 digits total OR two decimal places.
